apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app-container
          image: my-registry/my-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: 127.0.0.1
            - name: REDIS_PORT
              value: "6379"
